// Generated by github.com/davyxu/protoc-gen-sharpnet
// DO NOT EDIT!
// Source: core.proto
namespace gamedef
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestEchoACK")]
	public partial class TestEchoACK : global::ProtoBuf.IExtensible
	{
		public TestEchoACK() {}
		
		string _Content = "";
		bool _hasContent = false;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string Content
		{
			get { return _Content; }
			set { _Content = value; 
			      _hasContent = true;
			}
		}
		
		public bool HasContent
		{
			get { return _hasContent; }
			set { _hasContent = value; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}
